### ISSUE TITLE
Circle of Trust Errors

### ISSUE THREAD

**Issue by kvegesna** [systers/FirstAide-iOS#13]
I have found a small bug, after running the application on my Mac. I have updated XCode to the latest version:8.1 and have come across a bit of a glitch in the program. When I aimed to click the Circle of Trust Button, the application crashed and I received an error message. I made no alterations to the code and  I had no issues in running the application. I have tried to go through the code and find the error, but I was unable to exactly understand the cause of the error. I have attached the error message sent and hopefully you can look through to find the root of the error.

<img width="445" alt="bug in code pcsa-ios" src="https://cloud.githubusercontent.com/assets/13702834/20761811/3d2ceaf8-b74a-11e6-9e20-a8e9a488c13a.png">

**Comment by chamika** [comment]
@kvegesna In which branch do you work on?

**Comment by kvegesna** [comment]
I have been working on the original application. I simply followed the instructions in the README.md and this was the result after testing. I am working on the master branch.

**Comment by chamika** [comment]
The lifecycle of the development is like this. First developers make the changes in their repository. If the send development is finished, they send a PR to the /systers/develop branch. After merging the PR, the changes will reflect in the /systers/develop branch. From time to time(depending on the stability or the milestones of the project), we merge develop branch changes to master branch. 

If you check the commits of the two branches, [develop](https://github.com/systers/FirstAide-iOS/commits/develop) and [master](https://github.com/systers/FirstAide-iOS/commits/master) you can see that xcode 8 migration was done only in the develop branch.

So can you check whether this issue occurs in the develop branch as well?

**Comment by kvegesna** [comment]
Yes, I have tried it out with the develop branch and now the error is no longer there. I had suspected that incompatibility with the new XCode could've caused the issue. Thanks for your help!

**Comment by chamika** [comment]
The bug is invalid. Hence closing the issue
