### ISSUE TITLE
User Interface improvements that could be made.

### ISSUE THREAD

**Issue by dannymout** [systers/FirstAide-iOS#14]
I put together a document with some suggestions on improving the UI of the application:
https://docs.google.com/document/d/1l3mhB2zcFP-gjfR9swUWsMauJPhjqR7UzpjH3xeelcc/

**Comment by chamika** [comment]
These are some of the UI guidelines which are common to all FirstAide applications (iOS, Android, Web)
[https://github.com/systers/FirstAide-Android/issues/49](https://github.com/systers/FirstAide-Android/issues/49). Please go through them and get the idea.

You have suggested 4 improvements
1. Hamburger menu behavior - It is essential to have a hamburger menu. Therefore we cannot remove the menu icon. Instead, the issue in menu icon not showing in some screens should be fixed.

Outcome: Report an issue describing the current behavior and tell that menu icon should be visible on all screens.

2. Icons don’t match the UI of the app - Already there is a concern for this and new icons will be designed.

Outcome: Report an issue telling that it need to change the icons of Circle of Trusts screen.

3. Arrow buttons confuse the user - The same interface was implemented in both Android and Web applications. Therefore we cannot change it without the permission from peace corps. But this would be a good suggestion.

Outcome: Report an issue suggesting the tab based interface

4. Blue links aren’t visible in the background - This is a valid suggestion.
Outcome: Report an issue suggesting the UI change that you have described in the document.

**Comment by sandarumk** [comment]
@dannymout Good work on the improvements! Can you create 3 issues **separately** in the issue tracker as @chamika suggested. You only have to create issues which are described in outcome section in 1, 3 and 4.  When you are creating issues follow the general issue creating guidelines which are given in the READ Me file. Then we will create and publish a task to fix the issues, So that you can claim that task and fix an issue.

**Comment by chamika** [comment]
This issue was created for discussing the valid enhancements. Separate issues were created. Hence closing the issue
