### ISSUE TITLE
Hamburger menu needs to be accessible from all screens.   

### ISSUE THREAD

**Issue by dannymout** [systers/FirstAide-iOS#15]
Currently, in the app there is a hamburger menu on the main menu/home page. This doesn't need to be accessed from the main menu as there is already a menu on the screen. So, instead I suggest removing the hamburger menu only from the main menu. On the other screens, the back button needs to be replaced with the hamburger menu, so it actually has purpose.

<img src="http://i.imgur.com/Jo7EdQZ.png">

**Comment by chamika** [comment]
@dannymout Can you add screenshots of the current implementation and highlight the hamburger menu?Then the person who tries to fix will get a better understanding of the bug.

Removing back button will remove the back feature when going into multi-levels of screens. It would be great if we have both these features. An interface like having both hamburger and back will be good solution. Refer [UI design](https://github.com/systers/FirstAide-Android/issues/49) "Add forward and back buttons to header".

**Comment by dannymout** [comment]
@chamika Adding arrow buttons would confuse the user, I did read the UI design doc, but I don't think it's a good idea. The user can already access the sub-menus via the hamburger menu. More arrow buttons will overcomplicate the UI.

<img  width="400" src="http://i.imgur.com/kRyhkbs.png">

**Comment by jacqueline8711** [comment]
I'd like to work on this for the "Fix a reported bug" GCI task. 
@chamika If I can go ahead, should the screens have the  back arrow buttons and the hamburger menu or only the hamburger menu like @dannymout suggested?

**Comment by chamika** [comment]
@jacqueline8711 Yes go ahead and send a PR.

Although @dannymout suggested the behavior, Peace Corps already provided the guideline. So both hamburger menu and the arrow buttons should be there. Refer [UI designs](https://github.com/systers/FirstAide-Android/issues/49)

**Comment by chamika** [comment]
Make sure all the screens will have the same components and behaviour.

**Comment by chamika** [comment]
Bug fixed. Final behavior is both hamburger and buttons will co-exist in all view controllers.
