### ISSUE TITLE
Can't swipe down to the lower cards on "Safety Plan Worksheet"

### ISSUE THREAD

**Issue by dannymout** [systers/FirstAide-iOS#20]
While testing the app, I noticed that on the screens called "Safety Plan Worksheet" and "Peace Corps Commitment to Victims" both seem to have other yellow cards below the cards already on screen. It seems like I should be able to swipe up to see what is on the card below, but rather, it just doesn't move.

I made a GIF that shows what's happening. Github won't let me attach it, so here is the link: http://i.imgur.com/dZbqZoi.gifv

So as you can see dragging up does nothing even though there seems to be another card below.

**Comment by chamika** [comment]
This behavior was proposed by Peace Corps. Refer the linked video in the page https://github.com/systers/FirstAide-Android/issues/49
[Link to the demo video](https://drive.google.com/open?id=0B8cm8EBZg0GaZlNSdFpxeXJWelU) Similar UI component is showing in 2:10

Therefore changing the behavior need to be approved by them.

**Comment by dannymout** [comment]
@chamika I don't understand, aren't you suppose to be able to see the things on the cards below, I don't think it's normal behaviour.

**Comment by chamika** [comment]
@dannymout Action cards can be popped out by clicking the content. See this app walkthrough [video](https://youtu.be/K0iRimt26xM?t=119) 
It will sit there at the bottom in order to give the idea that the user can tap the content and see further details. So when there is no link, clicking any location within the content area will pop. Hope you get the idea.

**Comment by dannymout** [comment]
I'm going to close this. But, whoever came up with this UI clearly doesn't know what they're doing, it's quite incoherent, confusing. 

If I have to tap to access the lower cards, there should be some visual indication so the user knows this; as you can see I didn't understand.
