### ISSUE TITLE
Personal Security Strategies Button - Bug 

### ISSUE THREAD

**Issue by Isabel-S** [systers/FirstAide-iOS#21]
My task for GCI is: Find a bug! [FirstAide - iOS]
The bug is here that when you press the button Personal Security Strategies, it does not open to any page. I am also unsure if this was meant to be a title. If it is, then the format is off and many users may believe that this is a button. 
This is similar to the other issues on the buttons Sexual Assault Awareness and Policies and Glossary. 
The issue is on the menu sidebar and on the Safety Tools Page. I checked the storyboard and there is no segue to "Personal Strategies Scene" and no Scene in the first place.
Below is a link to google drive to see a video of the bug.
[(https://drive.google.com/file/d/0B5XB9ILn-H2MQ1dlc1dyTjBlS1k/view?usp=sharing)](url)

**Comment by chamika** [comment]
@Isabel-S That section is not yet implemented since the content was not provided by Peace Corps. Also, Sexual Assault Awareness and Policies and Glossary sections are not implemented. 
This is closing because the issue is invalid
