### ISSUE TITLE
 User Interface Enhancements: Suggestions for the UI[FirstAide - iOS]

### ISSUE THREAD

**Issue by YashBit** [systers/FirstAide-iOS#23]

**Comment by YashBit** [comment]
I compiled a list of suggestions for the improvement of the UI and UX for the First Aide App :

https://docs.google.com/document/d/1eznZmBrbtfADQJSnqVTaghhqffJBIXBZsxP20hygnHQ/edit

**Comment by jacqueline8711** [comment]
@YashBit Hi, the link you posted does't let everyone access the file. You should probably post one that allows reading access.

**Comment by YashBit** [comment]
https://docs.google.com/document/d/1eznZmBrbtfADQJSnqVTaghhqffJBIXBZsxP20hygnHQ/edit?usp=sharing

**Comment by YashBit** [comment]
Thanks

**Comment by chamika** [comment]
@YashBit Good work!!!. Please find the review of your suggestions

(i) Futile Navigation  &  Confusion - There is a bug in our issue list. Please go through that. #15 
(ii) A Larger and better animated HELP ME ! Button - Refer #16 
(iii) Proper Spacing In Navigation Bars And Better Text Display - This is valid
(iv) Betterment of the Scroll Views - Refer #22 
(v)Display of emergency and contact details in a Table Form - This is valid. Good suggestion. But changing UI need to be reflected in all iOS, Android and Web. 

Can you create separate GitHub **issue pages** describing current behavior and your suggestions for the (iii) and (v) ?

**Comment by YashBit** [comment]
Hi I am done .
Can I  solve the other issues ?
'

**Comment by chamika** [comment]
Yeah, Go on. 
Avoid issues tagged with "onhold" label. 
Before you start fixing, claim the issue by commenting that you like to work on it.

**Comment by chamika** [comment]
This was created for discussing the suggestions. Separate issues were created for the valid enhancements. Hence closing the issue
