### ISSUE TITLE
Bad Positioning of Action Labels

### ISSUE THREAD

**Issue by YashBit** [systers/FirstAide-iOS#30]
This bug is seen in the Safety Plan and in Peace Corps commitments scene .
This is the Action Button in FrameView of the various scenes 
![unknown-1](https://cloud.githubusercontent.com/assets/20094677/21080261/c945763e-bfd0-11e6-830c-b0833bcb7231.png)
![Uploading Unknown.png…]()

**Comment by chamika** [comment]
@YashBit An issue was already raised similar to this issue earlier and it describes the behavior. 
Refer: https://github.com/systers/FirstAide-iOS/issues/20
Please go through the issue list(both open and closed) before submitting an issue.

I'm closing the issue because the bug is invalid.
