### ISSUE TITLE
Cutting of Text In The Hamburger Menu

### ISSUE THREAD

**Issue by YashBit** [systers/FirstAide-iOS#33]
This is observed in the Hamburger Menu of the of the app . The text was to long for the menu to display thus they were cut off and thus not properly displayed . This will invariably lead to confusion of the users .

![simulator screen shot 12-dec-2016 4 21 36 am](https://cloud.githubusercontent.com/assets/20094677/21084318/aa5c73ba-c027-11e6-9961-0ba67bc8d32b.png)
![simulator screen shot 12-dec-2016 4 20 55 am](https://cloud.githubusercontent.com/assets/20094677/21084317/aa55231c-c027-11e6-94b2-51399d6bb584.png)

**Comment by chamika** [comment]
Yes, this needs to be fixed.

**Comment by YashBit** [comment]
May , I please go ahead with solving this ?

**Comment by tiferrei** [comment]
I'll start working in this.

**Comment by tiferrei** [comment]
Fixed, PR coming in a second.

**Comment by chamika** [comment]
Closing issue since this was fixed
