### ISSUE TITLE
login screen: subtitle cut off

### ISSUE THREAD

**Issue by jacqueline8711** [systers/FirstAide-iOS#37]
The subtitle ("A Safety Resource for Peace Corps Volunteers") is cut off on the sides. This happens with all iPhone sizes.
![firstaide-ios-loginbug](https://cloud.githubusercontent.com/assets/16260112/21267753/ebf7e4c6-c3ab-11e6-8b51-3d4567e770a7.jpg)

It should be displayed in two lines like it is in the main menu:
![howitshouldbe](https://cloud.githubusercontent.com/assets/16260112/21267783/1feb5b32-c3ac-11e6-9293-39a213b9f486.jpg)

**Comment by chamika** [comment]
Yes this should be fixed.

**Comment by ronakdev** [comment]
@chamika I'll be taking a look at this bug and will try to get it fixed within a week or so

**Comment by chamika** [comment]
@ronakdev Yes, go on. If you encounter any issues, let us know.

**Comment by tiferrei** [comment]
Hey, got this fixed, will open a PR soon.

**Comment by chamika** [comment]
@ronakdev Are you still working on this issue?

**Comment by ronakdev** [comment]
@chamika I fell sick but had fixed it, but @tiferrei's fix has already been merged, so there is no point.

**Comment by chamika** [comment]
@ronakdev. It's OK. I have merged the PR of @tiferrei. Hence closing the issue.
