### ISSUE TITLE
Text left out in Button on iPhone 5

### ISSUE THREAD

**Issue by jacqueline8711** [systers/FirstAide-iOS#38]
The label on the button "Coping with Unwanted Attention Strategies" in the Safety Tools menu is not fully readable on iPhone 5:
<img width="163" alt="firstaide_bug_2" src="https://cloud.githubusercontent.com/assets/16260112/21268346/a9356b6a-c3ae-11e6-9ad3-0c8898d14cfd.png">
It should automatically make a line break if the screen is too small for it to fit into one line. To fix this look at the button "Peace Corps’ Commitment to Victims of Sexual Assault" in the Support Service Menu. There it is right.

**Comment by chamika** [comment]
Yes, the text should be wrapped. Thank you reporting the bug.

**Comment by jacqueline8711** [comment]
Can I fix this?

**Comment by chamika** [comment]
Yes go ahead.

**Comment by chamika** [comment]
Bug fixed. Hence closing issue
