### ISSUE TITLE
Text overflowing in Get Help Now screen (iPhone 5)

### ISSUE THREAD

**Issue by jacqueline8711** [systers/FirstAide-iOS#39]
The text in the cards Post Staff in the Get Help Now screen are slightly overflowing on an iPhone 5. This is not an issue for the Other Staff cards so they probably contain the solution to the issue. 

<img width="317" alt="firstaide_bug" src="https://cloud.githubusercontent.com/assets/16260112/21268631/d7e5dc00-c3af-11e6-9934-c8225c769c2a.png">

**Comment by fennecus-z** [comment]
Will attempt to fix

**Comment by chamika** [comment]
Yes go on
