### ISSUE TITLE
Deprecated code (in iOS 8.0)

### ISSUE THREAD

**Issue by ingridt123** [systers/FirstAide-iOS#49]
App still works but this line of code was deprecated in iOS 8.0.
Code is in loadContactPhotos function within CircleOfTrustViewController class.

<img width="690" alt="screen shot 2017-01-11 at 7 15 25 pm" src="https://cloud.githubusercontent.com/assets/19776302/21846577/bbd8951a-d832-11e6-9bd3-d09221e286fc.png">

**Comment by tiferrei** [comment]
Can I work on this? (already have it fixed)

**Comment by ingridt123** [comment]
ok thanks @tiferrei!

**Comment by tiferrei** [comment]
No problem @ingridt123! :)

**Comment by tiferrei** [comment]
Done, PR submitted.
