### ISSUE TITLE
Update ReadMe and Code

### ISSUE THREAD

**Issue by MeepyMay** [systers/FirstAide-iOS#5]
Hi @chamika ... @rosariorobinson and I are trying to prepare for GHC Open source day and we need help with the ReadME. Is the current ReadMe updated? The goal is to environment ready on a USB in case there are WiFi issues.

Is it possible to have README updated and submit a PR with any additional GSoC code by Friday or Saturday (10/14 or 10/15 respectively) at the latest? We really need your help.

Please use this issue to update us on this task.

**Comment by chamika** [comment]
As far as I remember the README is up to date. I'll go through the file again and make changes if necessary. 

Last few weeks I was trying to convert the code to work with xcode 8 and swift 3.  But couldn't complete that. After the auto conversion it appears some build errors. So it's better to stay with xcode 7 build which is already pushed to repo. 

If you have any issues please let me know.

**Comment by chamika** [comment]
@MeepyMay @rosariorobinson 
The code has all the implementation in the GSoC period.

Do you need any more changes done to README? It has all the information necessary on getting started. If you need any more changes, please let me know.
