### ISSUE TITLE
"Peace Corp's Commitments" view not fully accessible on 4S

### ISSUE THREAD

**Issue by tiferrei** [systers/FirstAide-iOS#54]
The "Peace Corp's Commitments" is not fully accessible on the iPhone 4S' screen, although the main content is "swipeable" it does not allow the user to reach for the lower card, a touch event on the lower orange button is not recognised.

Screenshot: 
![simulator screen shot 13 jan 2017 16 46 08](https://cloud.githubusercontent.com/assets/8849915/21937699/3a79fa5c-d9b0-11e6-9dde-ea5ccd83d485.png)

**Comment by chamika** [comment]
@tiferrei if you tap on the content ( text in the dark green area), the yellow card will pop up and you can access the content. Please go through the closed issues to get the reasoning behind this.

**Comment by tiferrei** [comment]
Just for the record and as general feedback, that makes zero sense, the user would never think like that. UI is just like a joke, if you have to explain it, it's crap.

**Comment by chamika** [comment]
Noted. https://github.com/systers/FirstAide-iOS/issues/20

**Comment by tiferrei** [comment]
I understand it, you're following orders, but the user won't understand that, the user won't go "Oh of course, it's because the android app works like this.", he will just say "Why the hell did you make it like that?"
And if this also happens on the android app, maybe it's time to also change it.
