### ISSUE TITLE
"Circle Of Trust" ignores declined contacts access

### ISSUE THREAD

**Issue by tiferrei** [systers/FirstAide-iOS#55]
Even though I have declined the app access to my contacts, it still reads it and perfectly presents/picks numbers from my contacts. There's something seriously wrong in here, if this is not fixed, it won't ever reach the App Store, there's no way Apple's accepting this.

Proof: [Bug.zip](https://github.com/systers/FirstAide-iOS/files/704984/Bug.zip)

**Comment by chamika** [comment]
Good finding, can you suggest the correct behavior?

**Comment by tiferrei** [comment]
This one blows me a bit out of the water to be honest, in theory, this is something we can't control, Apple private APIs, the PermissionAccess delegate prompts the user when we need access, and then relays the data if we allow it, this looks like an iOS bug.

What we can do though, is check if we have permission to access the contacts, there's a public API for that, and if we don't well just hide the contact book icon opening the contacts. That will also prevent access errors just in case the user declines access and then accidentally taps it, a call would be made requesting the contacts, an error would be thrown back instead of the data, boom, crash.

**Comment by chamika** [comment]
Anyway, it seems like we need to avoid showing contacts if the user rejects the permission. So this is a valid bug.

**Comment by tiferrei** [comment]
Seems simple enough, request the access status to the manager, if it's blocked, hide the button. 
Can I work on this, please?

**Comment by chamika** [comment]
Yes, go ahead. If you are not completed the bug fixing task in GCI, you can claim that and submit this fix.

**Comment by tiferrei** [comment]
PR submitted.
