### ISSUE TITLE
Text does not fit in several Sexual Assault Awareness screens (iPhone 5 and 5s)

### ISSUE THREAD

**Issue by ingridt123** [systers/FirstAide-iOS#56]
I have found 5 examples where the explanations/answers on the Sexual Assault Awareness screens don't fit in the box.

iPhone 5/5s
<img width="318" alt="1 what is sexual assault" src="https://cloud.githubusercontent.com/assets/19776302/21953242/6c214a08-da6c-11e6-8668-9fce970b7aae.png">
<img width="319" alt="2 common question 3" src="https://cloud.githubusercontent.com/assets/19776302/21953243/6c22e53e-da6c-11e6-83d6-da8c0ea8e84d.png">
<img width="322" alt="3 common question 5" src="https://cloud.githubusercontent.com/assets/19776302/21953245/6c2570f6-da6c-11e6-93ec-0fee43130810.png">
<img width="323" alt="4 effects of sexual assault" src="https://cloud.githubusercontent.com/assets/19776302/21953244/6c255ee0-da6c-11e6-9822-7c175ff282b5.png">
<img width="321" alt="5 what is sexual harrassment" src="https://cloud.githubusercontent.com/assets/19776302/21953246/6c287030-da6c-11e6-8ff4-10314f0a246d.png">

iPhone 6 and above (what it is supposed to look like)
<img width="371" alt="1 what is sexual assault" src="https://cloud.githubusercontent.com/assets/19776302/21953250/80cf65fc-da6c-11e6-82ab-d96a8e109161.png">
<img width="375" alt="2 common question 3" src="https://cloud.githubusercontent.com/assets/19776302/21953251/80d65416-da6c-11e6-8cbf-b021efc330e1.png">
<img width="375" alt="3 common question 5" src="https://cloud.githubusercontent.com/assets/19776302/21953252/80d85d10-da6c-11e6-87cb-083f2b6225d3.png">
<img width="379" alt="4 effects of sexual assault" src="https://cloud.githubusercontent.com/assets/19776302/21953253/80db1398-da6c-11e6-877f-ef606aaedd9b.png">
<img width="377" alt="5 what is sexual harrassment" src="https://cloud.githubusercontent.com/assets/19776302/21953259/d3c84198-da6c-11e6-915d-8dc107ffb0a3.png">

**Comment by jacqueline8711** [comment]
@ingridt123 What do you mean? All the dark green boxes are vertically scrollable if there is too much text to fit in there.

**Comment by ingridt123** [comment]
@jacqueline8711 the scroll doesn't always work on the older iPhone versions

**Comment by jacqueline8711** [comment]
But the scroll views in the rest of the screens work? I tested it on the iPhone 5 and 5s emulator and there it works fine...

**Comment by ingridt123** [comment]
Ok maybe it's just an issue on my side. Thanks for pointing it out!

**Comment by jacqueline8711** [comment]
@ingridt123 Did you run it on a real device or also only on the emulator?
