### ISSUE TITLE
Cannot click on "Personal Security Strategies" button

### ISSUE THREAD

**Issue by ingridt123** [systers/FirstAide-iOS#58]
Cannot click on "Personal Security Strategies" button in the Safety Tools section.

**Comment by jacqueline8711** [comment]
Hi, please check all existing issues first, also the ones that are closed. Refer to #31 and #21

**Comment by ingridt123** [comment]
Sorry then perhaps an enhancement idea -- change color of buttons of sections not yet built so that users know that it is not a bug.

**Comment by sandarumk** [comment]
@ingridt123 Please open a separate issue if you are suggesting new improvements. Do not reopen and use the same issue reference.
