### ISSUE TITLE
Implement Policies and Glossary screen(s)

### ISSUE THREAD

**Issue by chamika** [systers/FirstAide-iOS#8]
App should support all the features which are currently available in FirstAide-Android App. 
Therefore we need to develop Policies and Glossary screens and menu navigation.

Steps
1. Go through the Android application screens before start implementing it. [Source](https://github.com/systers/FirstAide-Android)

2. Submit a design/mockup screens which covers Android App features. But screens should adhere the iOS design guidelines

3. Once the design/mockup screens are finalized, we can start the development

The content for these screens are available in this [document](https://drive.google.com/file/d/0B8cm8EBZg0GaQy1CUkRUOXhWZUE/view)

The screen should navigate from main screen button and the slide menu.
![policy](https://cloud.githubusercontent.com/assets/754909/20606649/62ec9cd6-b298-11e6-9048-e91667631260.png)

**Comment by YashBit** [comment]
Hi , please can this task be assigned to me ?

**Comment by chamika** [comment]
You have claimed another issue #7. It's better to start working on a single issue and once it's finished, move on to another. Please select one issue you like to work?

**Comment by YashBit** [comment]
I would like to go ahead with this one .

**Comment by chamika** [comment]
OK, Go ahead. Before developing anything, show us some mock screens  which you are going to implement

**Comment by YashBit** [comment]
Ok , Hi  There is no task available for solving issues . What do you suggest ?

**Comment by chamika** [comment]
@YashBit, You can start with the design first
[https://codein.withgoogle.com/dashboard/tasks/5195875135520768/](https://codein.withgoogle.com/dashboard/tasks/5195875135520768/)

**Comment by YashBit** [comment]
I just wanted to get the process clear . After the mockup screens are approved I can go ahead and develop them , or do I just have the task of making the mockup screens asingned to me 
?
Thanks.

**Comment by YashBit** [comment]
Okay , I have claimed this task : 
https://codein.withgoogle.com/dashboard/task-instances/5132514576302080/
It says I have to solve a bug , This issue doesn't have a bug label . What should I do  ?

**Comment by YashBit** [comment]
Hi , Please Can you send me screenshots of the Android app in Policies and Glossary Screen .

**Comment by jacqueline8711** [comment]
@YashBit 
Here are screenshots of the policy and glossary screens in Android:
![screenshot_20161208-143757](https://cloud.githubusercontent.com/assets/16260112/21012225/488f18c4-bd55-11e6-86bf-811694b14c9c.png)
![screenshot_20161208-143804](https://cloud.githubusercontent.com/assets/16260112/21012226/48baff34-bd55-11e6-9fa2-683327f92cfe.png)
![screenshot_20161208-143842](https://cloud.githubusercontent.com/assets/16260112/21012229/48bc8bd8-bd55-11e6-8ae0-15fd3a21b4c8.png)
![screenshot_20161208-143908](https://cloud.githubusercontent.com/assets/16260112/21012228/48bb9566-bd55-11e6-9053-40b5263903ea.png)

**Comment by YashBit** [comment]
Thanks a lot

**Comment by YashBit** [comment]
<img width="313" alt="screen shot 2016-12-08 at 9 49 17 pm" src="https://cloud.githubusercontent.com/assets/20094677/21018184/f21ce100-bd91-11e6-971d-46fed7960386.png">
<img width="312" alt="screen shot 2016-12-08 at 10 00 39 pm" src="https://cloud.githubusercontent.com/assets/20094677/21018194/f745a608-bd91-11e6-99e3-750deef8016d.png">

**Comment by YashBit** [comment]
I know , the colour is  a little off , the software that I used wasn't accepting the hex value .
I will keep the Further Resources View the same .
May I go ahead with the development ?

**Comment by chamika** [comment]
@YashBit I think you have confused GCI tasks. As I mentioned you earlier there is a separate task which covers designing Policies and Glossary screen
[https://codein.withgoogle.com/dashboard/tasks/5195875135520768/](https://codein.withgoogle.com/dashboard/tasks/5195875135520768/)

It's better to claim this task instead of bug fixing task. Because this is not a bug of the app. Therefore we cannot categorize this as a bug fixing. You can abandon bug fixing task and start working on this task.

Since a design should cover all the screens, you may need to add design screens of "Glossary" and "Further Resources" as well. Especially "Glossary" has the feature to search. We like to see how these screens fit into iOS interface. 

After you complete this, we'll publish a new task to develop the designed screens.

**Comment by YashBit** [comment]
Yes , I understand . I  will surely complete the rest of the mockups . As for the deign task , it has  a beginner tag , So I cannot claim it . 
What should I do ?

**Comment by YashBit** [comment]
<img width="313" alt="screen shot 2016-12-09 at 7 45 15 am" src="https://cloud.githubusercontent.com/assets/20094677/21035682/cc44b25a-bde6-11e6-8369-0ff9b554547b.png">
<img width="315" alt="screen shot 2016-12-09 at 7 45 27 am" src="https://cloud.githubusercontent.com/assets/20094677/21035685/cddc321e-bde6-11e6-9dcd-d98c7a34e268.png">
<img width="311" alt="screen shot 2016-12-09 at 7 54 23 am" src="https://cloud.githubusercontent.com/assets/20094677/21035686/cf4eb6a8-bde6-11e6-9aca-bf95f639ab14.png">
<img width="312" alt="screen shot 2016-12-09 at 8 08 54 am" src="https://cloud.githubusercontent.com/assets/20094677/21035687/d1a519a6-bde6-11e6-93a2-aeff4b8093d1.png">

**Comment by YashBit** [comment]
@Chamika Are these mockup screens okay ?

**Comment by chamika** [comment]
@YashBit I think you have already completed your beginner tasks. That is why you cannot claim the design task. 
Mockup screens seem to be OK. We'll publish separate development task in GCI and let you know. Until the task is published and claimed by you, please refrain from developing. We'll add the GCI task link as a comment once it is published.

**Comment by chamika** [comment]
@YashBit I think you have to wait until the design task is completed. Please work on another task.

**Comment by JosephBywater** [comment]
@chamika Here's my finished screens: 
![firstaide-policies](https://cloud.githubusercontent.com/assets/5558617/21107900/3499a31e-c08b-11e6-8ed7-93c58e406a5b.png)
![furtherinfo-sub](https://cloud.githubusercontent.com/assets/5558617/21107898/3497353e-c08b-11e6-91ba-658d0f37fc00.png)
![glossary-sub](https://cloud.githubusercontent.com/assets/5558617/21107897/349682b0-c08b-11e6-99a2-f16576ce94bb.png)
![policies-sub](https://cloud.githubusercontent.com/assets/5558617/21107899/34999ea0-c08b-11e6-8692-8e6e341c49c2.png)

**Comment by chamika** [comment]
@JosephBywater Thank you the designs. I think it would be great to have following changes in mockups

It need to replace the title with navigation bar title. iOS app does not use two titles.
Ex: Further resources - Remove "Further resources" title and replace "Policies and Glossary" with that title.

Glossary buttons should have an indicator to show that they can be expand. Ex: down arrow or similar

**Comment by JosephBywater** [comment]
Ok, I think I have implemented those changed @chamika 

![firstaide-policies](https://cloud.githubusercontent.com/assets/5558617/21131363/3109cb4a-c106-11e6-8988-295fc119df61.png)
![furtherinfo-sub](https://cloud.githubusercontent.com/assets/5558617/21131366/310e77c6-c106-11e6-835f-ba696c952b40.png)
![glossary-sub](https://cloud.githubusercontent.com/assets/5558617/21131365/310e426a-c106-11e6-99fc-2f7d812ae003.png)
![policies-sub](https://cloud.githubusercontent.com/assets/5558617/21131364/310e1cd6-c106-11e6-82eb-00541f524b2a.png)

**Comment by chamika** [comment]
It looks good. Thanks @JosephBywater

**Comment by chamika** [comment]
@YashBit Go ahead and start developing the screens according to @JosephBywater 's designs

**Comment by YashBit** [comment]
@chamika  Ok , Please could someone send a screenshot of the Glossary Scene with Burglary in particular (Android) . I just want to see how it is implemented in Android . 
Thanks

**Comment by jacqueline8711** [comment]
@YashBit I hope this helps:

![screenshot_20161214-174359](https://cloud.githubusercontent.com/assets/16260112/21191535/bbbc30e6-c225-11e6-925d-0ba024ac4746.png)
![screenshot_20161214-174353](https://cloud.githubusercontent.com/assets/16260112/21191536/bbe33aba-c225-11e6-9297-3ea6e6f32d4a.png)

**Comment by YashBit** [comment]
@jacqueline8711  Thanks

**Comment by chamika** [comment]
I think you might need to go through the other topics as well. So it will be easy for you to setup Android Environment. Follow the repo to setup it. Readme is pretty descriptive. [https://github.com/systers/FirstAide-Android](https://github.com/systers/FirstAide-Android)

If you have difficulties let us know.

**Comment by jacqueline8711** [comment]
Can I work on this? I claimed the task for developing these screens because @YashBit did not seem to work on it after all.

**Comment by YashBit** [comment]
@jacqueline8711 Hi , I did try a lot to solve the problem , but I failed to understand how to populate the UITextView . But I don't have any problem with  you being assigned to the task . All the best !

**Comment by jacqueline8711** [comment]
Thanks, @YashBit ! I'll go ahead with it then.

**Comment by chamika** [comment]
@jacqueline8711 OK go ahead

**Comment by chamika** [comment]
This is complete. Hence closing the issue
